### ISSUE TITLE
Verify Spellcheck workflow in all devon repositories

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/.github#172]
Verify the spell check workflow in all repos and prepare a list of repos which are in failure.

**Comment by suprishi** [comment]
Spellcheck workflow is not able to find the configuration file only in the devon4j repository. It is throwing the following exception:
`ValueError: Unable to find or load pyspelling configuration from spellcheck.yaml, for more details on configuration please read https://facelessuser.github.io/pyspelling/configuration/`

 In every other repo it is working as expected, that is, it is either displaying the spelling mistakes or passing successfully

**Comment by suprishi** [comment]
Updated the spellcheck yml file in devon4j to reuse the workflow from the central .github repository. Created a a PR https://github.com/devonfw/devon4j/pull/560
