### ISSUE TITLE
Stale bot needed in all repository

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/.github#173]
Stale bot required to added to all repositories.
https://github.com/probot/stale

**Comment by sujith-mn** [comment]
Here is a bot:
https://github.com/marketplace/stale

**Comment by abhaychandel-capgemini** [comment]
SCOPE
We can start with the following
devon4j
devon4node
devon4ng
cobigen
ide
and later we can add to others as well.

SCENARIO
1. Any issue open and inactive in past 30 days, mssage: won't fix, after 7 days close

NOTE: Refer mythaistar for current implementation.

**Comment by ssarmokadam** [comment]
merged PRs
